version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs:python3.6-nodejs11

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test
      - run: npm run build
      - aws-s3/sync:
          from: dist
          to: 's3://tw.crispinto.com'
          arguments: |
            --cache-control "max-age=86400"
          overwrite: true