version: 2.1
jobs:
  build:
    docker:
      - image: cdpinto/aws-node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test
      - run: npm run build
      - run:
          name: Configure AWS
          command: |
            aws configure set aws_access_key_id \
              $AWS_ACCESS_KEY_ID \
              --profile default
            aws configure set aws_secret_access_key \
              $AWS_SECRET_ACCESS_KEY \
              --profile default
            aws configure set region $AWS_REGION \
              --profile default
      - deploy:
          name: Deploy to S3
          command: |
            aws s3 sync \
              dist s3://tw.crispinto.com \
              --cache-control "max-age=86400" \
              --delete
